name: Generate Docs

on:
  repository_dispatch:
    types: [generate-docs]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - run: ./update.sh
      - run: git add .
      - run: git commit -m "Update docs"
      - run: git push origin main
