name: Generate Docs

on:
  repository_dispatch:
    types: [generate-docs]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          submodules: recursive
      - run: yarn install
      - run: yarn make-docs
      - name: Commit changes
        run: |
          git config --global user.email "gitbot@thirdweb.com"
          git config --global user.name "thirdweb Git Bot"
          git status
          git add .
          git commit -m "Update docs"
          git push origin main
